// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PARKINGSPOT_FB_H_
#define FLATBUFFERS_GENERATED_PARKINGSPOT_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace fb {

struct ParkingSpot;
struct ParkingSpotBuilder;
struct ParkingSpotT;

struct ParkingSpotRow;
struct ParkingSpotRowBuilder;
struct ParkingSpotRowT;

struct ParkingSpotT : public ::flatbuffers::NativeTable {
  typedef ParkingSpot TableType;
  std::vector<std::unique_ptr<fb::ParkingSpotRowT>> ParkingSpots{};
  ParkingSpotT() = default;
  ParkingSpotT(const ParkingSpotT &o);
  ParkingSpotT(ParkingSpotT&&) FLATBUFFERS_NOEXCEPT = default;
  ParkingSpotT &operator=(ParkingSpotT o) FLATBUFFERS_NOEXCEPT;
};

struct ParkingSpot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ParkingSpotT NativeTableType;
  typedef ParkingSpotBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARKINGSPOTS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fb::ParkingSpotRow>> *ParkingSpots() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fb::ParkingSpotRow>> *>(VT_PARKINGSPOTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARKINGSPOTS) &&
           verifier.VerifyVector(ParkingSpots()) &&
           verifier.VerifyVectorOfTables(ParkingSpots()) &&
           verifier.EndTable();
  }
  ParkingSpotT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ParkingSpotT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ParkingSpot> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ParkingSpotT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ParkingSpotBuilder {
  typedef ParkingSpot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ParkingSpots(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fb::ParkingSpotRow>>> ParkingSpots) {
    fbb_.AddOffset(ParkingSpot::VT_PARKINGSPOTS, ParkingSpots);
  }
  explicit ParkingSpotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ParkingSpot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ParkingSpot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ParkingSpot> CreateParkingSpot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fb::ParkingSpotRow>>> ParkingSpots = 0) {
  ParkingSpotBuilder builder_(_fbb);
  builder_.add_ParkingSpots(ParkingSpots);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ParkingSpot> CreateParkingSpotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fb::ParkingSpotRow>> *ParkingSpots = nullptr) {
  auto ParkingSpots__ = ParkingSpots ? _fbb.CreateVector<::flatbuffers::Offset<fb::ParkingSpotRow>>(*ParkingSpots) : 0;
  return fb::CreateParkingSpot(
      _fbb,
      ParkingSpots__);
}

::flatbuffers::Offset<ParkingSpot> CreateParkingSpot(::flatbuffers::FlatBufferBuilder &_fbb, const ParkingSpotT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ParkingSpotRowT : public ::flatbuffers::NativeTable {
  typedef ParkingSpotRow TableType;
  uint32_t Id = 0;
  uint32_t StationId = 0;
  uint32_t WorldTypeId = 0;
  std::unique_ptr<fb::tuple_float32_float32_float32T> CenterPosition{};
  std::unique_ptr<fb::tuple_float32_float32_float32_float32T> Rotation{};
  std::unique_ptr<fb::tuple_float32_float32_float32T> Scale{};
  std::string PrefabPath{};
  ParkingSpotRowT() = default;
  ParkingSpotRowT(const ParkingSpotRowT &o);
  ParkingSpotRowT(ParkingSpotRowT&&) FLATBUFFERS_NOEXCEPT = default;
  ParkingSpotRowT &operator=(ParkingSpotRowT o) FLATBUFFERS_NOEXCEPT;
};

struct ParkingSpotRow FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ParkingSpotRowT NativeTableType;
  typedef ParkingSpotRowBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_STATIONID = 6,
    VT_WORLDTYPEID = 8,
    VT_CENTERPOSITION = 10,
    VT_ROTATION = 12,
    VT_SCALE = 14,
    VT_PREFABPATH = 16
  };
  uint32_t Id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  uint32_t StationId() const {
    return GetField<uint32_t>(VT_STATIONID, 0);
  }
  uint32_t WorldTypeId() const {
    return GetField<uint32_t>(VT_WORLDTYPEID, 0);
  }
  const fb::tuple_float32_float32_float32 *CenterPosition() const {
    return GetPointer<const fb::tuple_float32_float32_float32 *>(VT_CENTERPOSITION);
  }
  const fb::tuple_float32_float32_float32_float32 *Rotation() const {
    return GetPointer<const fb::tuple_float32_float32_float32_float32 *>(VT_ROTATION);
  }
  const fb::tuple_float32_float32_float32 *Scale() const {
    return GetPointer<const fb::tuple_float32_float32_float32 *>(VT_SCALE);
  }
  const ::flatbuffers::String *PrefabPath() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PREFABPATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_STATIONID, 4) &&
           VerifyField<uint32_t>(verifier, VT_WORLDTYPEID, 4) &&
           VerifyOffset(verifier, VT_CENTERPOSITION) &&
           verifier.VerifyTable(CenterPosition()) &&
           VerifyOffset(verifier, VT_ROTATION) &&
           verifier.VerifyTable(Rotation()) &&
           VerifyOffset(verifier, VT_SCALE) &&
           verifier.VerifyTable(Scale()) &&
           VerifyOffset(verifier, VT_PREFABPATH) &&
           verifier.VerifyString(PrefabPath()) &&
           verifier.EndTable();
  }
  ParkingSpotRowT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ParkingSpotRowT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ParkingSpotRow> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ParkingSpotRowT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ParkingSpotRowBuilder {
  typedef ParkingSpotRow Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Id(uint32_t Id) {
    fbb_.AddElement<uint32_t>(ParkingSpotRow::VT_ID, Id, 0);
  }
  void add_StationId(uint32_t StationId) {
    fbb_.AddElement<uint32_t>(ParkingSpotRow::VT_STATIONID, StationId, 0);
  }
  void add_WorldTypeId(uint32_t WorldTypeId) {
    fbb_.AddElement<uint32_t>(ParkingSpotRow::VT_WORLDTYPEID, WorldTypeId, 0);
  }
  void add_CenterPosition(::flatbuffers::Offset<fb::tuple_float32_float32_float32> CenterPosition) {
    fbb_.AddOffset(ParkingSpotRow::VT_CENTERPOSITION, CenterPosition);
  }
  void add_Rotation(::flatbuffers::Offset<fb::tuple_float32_float32_float32_float32> Rotation) {
    fbb_.AddOffset(ParkingSpotRow::VT_ROTATION, Rotation);
  }
  void add_Scale(::flatbuffers::Offset<fb::tuple_float32_float32_float32> Scale) {
    fbb_.AddOffset(ParkingSpotRow::VT_SCALE, Scale);
  }
  void add_PrefabPath(::flatbuffers::Offset<::flatbuffers::String> PrefabPath) {
    fbb_.AddOffset(ParkingSpotRow::VT_PREFABPATH, PrefabPath);
  }
  explicit ParkingSpotRowBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ParkingSpotRow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ParkingSpotRow>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ParkingSpotRow> CreateParkingSpotRow(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Id = 0,
    uint32_t StationId = 0,
    uint32_t WorldTypeId = 0,
    ::flatbuffers::Offset<fb::tuple_float32_float32_float32> CenterPosition = 0,
    ::flatbuffers::Offset<fb::tuple_float32_float32_float32_float32> Rotation = 0,
    ::flatbuffers::Offset<fb::tuple_float32_float32_float32> Scale = 0,
    ::flatbuffers::Offset<::flatbuffers::String> PrefabPath = 0) {
  ParkingSpotRowBuilder builder_(_fbb);
  builder_.add_PrefabPath(PrefabPath);
  builder_.add_Scale(Scale);
  builder_.add_Rotation(Rotation);
  builder_.add_CenterPosition(CenterPosition);
  builder_.add_WorldTypeId(WorldTypeId);
  builder_.add_StationId(StationId);
  builder_.add_Id(Id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ParkingSpotRow> CreateParkingSpotRowDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Id = 0,
    uint32_t StationId = 0,
    uint32_t WorldTypeId = 0,
    ::flatbuffers::Offset<fb::tuple_float32_float32_float32> CenterPosition = 0,
    ::flatbuffers::Offset<fb::tuple_float32_float32_float32_float32> Rotation = 0,
    ::flatbuffers::Offset<fb::tuple_float32_float32_float32> Scale = 0,
    const char *PrefabPath = nullptr) {
  auto PrefabPath__ = PrefabPath ? _fbb.CreateString(PrefabPath) : 0;
  return fb::CreateParkingSpotRow(
      _fbb,
      Id,
      StationId,
      WorldTypeId,
      CenterPosition,
      Rotation,
      Scale,
      PrefabPath__);
}

::flatbuffers::Offset<ParkingSpotRow> CreateParkingSpotRow(::flatbuffers::FlatBufferBuilder &_fbb, const ParkingSpotRowT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ParkingSpotT::ParkingSpotT(const ParkingSpotT &o) {
  ParkingSpots.reserve(o.ParkingSpots.size());
  for (const auto &ParkingSpots_ : o.ParkingSpots) { ParkingSpots.emplace_back((ParkingSpots_) ? new fb::ParkingSpotRowT(*ParkingSpots_) : nullptr); }
}

inline ParkingSpotT &ParkingSpotT::operator=(ParkingSpotT o) FLATBUFFERS_NOEXCEPT {
  std::swap(ParkingSpots, o.ParkingSpots);
  return *this;
}

inline ParkingSpotT *ParkingSpot::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ParkingSpotT>(new ParkingSpotT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ParkingSpot::UnPackTo(ParkingSpotT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ParkingSpots(); if (_e) { _o->ParkingSpots.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->ParkingSpots[_i]) { _e->Get(_i)->UnPackTo(_o->ParkingSpots[_i].get(), _resolver); } else { _o->ParkingSpots[_i] = std::unique_ptr<fb::ParkingSpotRowT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->ParkingSpots.resize(0); } }
}

inline ::flatbuffers::Offset<ParkingSpot> ParkingSpot::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ParkingSpotT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateParkingSpot(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ParkingSpot> CreateParkingSpot(::flatbuffers::FlatBufferBuilder &_fbb, const ParkingSpotT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ParkingSpotT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ParkingSpots = _o->ParkingSpots.size() ? _fbb.CreateVector<::flatbuffers::Offset<fb::ParkingSpotRow>> (_o->ParkingSpots.size(), [](size_t i, _VectorArgs *__va) { return CreateParkingSpotRow(*__va->__fbb, __va->__o->ParkingSpots[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fb::CreateParkingSpot(
      _fbb,
      _ParkingSpots);
}

inline ParkingSpotRowT::ParkingSpotRowT(const ParkingSpotRowT &o)
      : Id(o.Id),
        StationId(o.StationId),
        WorldTypeId(o.WorldTypeId),
        CenterPosition((o.CenterPosition) ? new fb::tuple_float32_float32_float32T(*o.CenterPosition) : nullptr),
        Rotation((o.Rotation) ? new fb::tuple_float32_float32_float32_float32T(*o.Rotation) : nullptr),
        Scale((o.Scale) ? new fb::tuple_float32_float32_float32T(*o.Scale) : nullptr),
        PrefabPath(o.PrefabPath) {
}

inline ParkingSpotRowT &ParkingSpotRowT::operator=(ParkingSpotRowT o) FLATBUFFERS_NOEXCEPT {
  std::swap(Id, o.Id);
  std::swap(StationId, o.StationId);
  std::swap(WorldTypeId, o.WorldTypeId);
  std::swap(CenterPosition, o.CenterPosition);
  std::swap(Rotation, o.Rotation);
  std::swap(Scale, o.Scale);
  std::swap(PrefabPath, o.PrefabPath);
  return *this;
}

inline ParkingSpotRowT *ParkingSpotRow::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ParkingSpotRowT>(new ParkingSpotRowT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ParkingSpotRow::UnPackTo(ParkingSpotRowT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = Id(); _o->Id = _e; }
  { auto _e = StationId(); _o->StationId = _e; }
  { auto _e = WorldTypeId(); _o->WorldTypeId = _e; }
  { auto _e = CenterPosition(); if (_e) { if(_o->CenterPosition) { _e->UnPackTo(_o->CenterPosition.get(), _resolver); } else { _o->CenterPosition = std::unique_ptr<fb::tuple_float32_float32_float32T>(_e->UnPack(_resolver)); } } else if (_o->CenterPosition) { _o->CenterPosition.reset(); } }
  { auto _e = Rotation(); if (_e) { if(_o->Rotation) { _e->UnPackTo(_o->Rotation.get(), _resolver); } else { _o->Rotation = std::unique_ptr<fb::tuple_float32_float32_float32_float32T>(_e->UnPack(_resolver)); } } else if (_o->Rotation) { _o->Rotation.reset(); } }
  { auto _e = Scale(); if (_e) { if(_o->Scale) { _e->UnPackTo(_o->Scale.get(), _resolver); } else { _o->Scale = std::unique_ptr<fb::tuple_float32_float32_float32T>(_e->UnPack(_resolver)); } } else if (_o->Scale) { _o->Scale.reset(); } }
  { auto _e = PrefabPath(); if (_e) _o->PrefabPath = _e->str(); }
}

inline ::flatbuffers::Offset<ParkingSpotRow> ParkingSpotRow::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ParkingSpotRowT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateParkingSpotRow(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ParkingSpotRow> CreateParkingSpotRow(::flatbuffers::FlatBufferBuilder &_fbb, const ParkingSpotRowT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ParkingSpotRowT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _Id = _o->Id;
  auto _StationId = _o->StationId;
  auto _WorldTypeId = _o->WorldTypeId;
  auto _CenterPosition = _o->CenterPosition ? Createtuple_float32_float32_float32(_fbb, _o->CenterPosition.get(), _rehasher) : 0;
  auto _Rotation = _o->Rotation ? Createtuple_float32_float32_float32_float32(_fbb, _o->Rotation.get(), _rehasher) : 0;
  auto _Scale = _o->Scale ? Createtuple_float32_float32_float32(_fbb, _o->Scale.get(), _rehasher) : 0;
  auto _PrefabPath = _o->PrefabPath.empty() ? 0 : _fbb.CreateString(_o->PrefabPath);
  return fb::CreateParkingSpotRow(
      _fbb,
      _Id,
      _StationId,
      _WorldTypeId,
      _CenterPosition,
      _Rotation,
      _Scale,
      _PrefabPath);
}

inline const fb::ParkingSpot *GetParkingSpot(const void *buf) {
  return ::flatbuffers::GetRoot<fb::ParkingSpot>(buf);
}

inline const fb::ParkingSpot *GetSizePrefixedParkingSpot(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::ParkingSpot>(buf);
}

inline bool VerifyParkingSpotBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::ParkingSpot>(nullptr);
}

inline bool VerifySizePrefixedParkingSpotBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::ParkingSpot>(nullptr);
}

inline void FinishParkingSpotBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::ParkingSpot> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedParkingSpotBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::ParkingSpot> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<fb::ParkingSpotT> UnPackParkingSpot(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<fb::ParkingSpotT>(GetParkingSpot(buf)->UnPack(res));
}

inline std::unique_ptr<fb::ParkingSpotT> UnPackSizePrefixedParkingSpot(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<fb::ParkingSpotT>(GetSizePrefixedParkingSpot(buf)->UnPack(res));
}

}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_PARKINGSPOT_FB_H_
